using System.Text.Json;
using System.Text.Json.Serialization;
using TerraformMerge.Engine;

namespace TerraformMerge.Tests;

/// <summary>
/// Data-driven regression tests over the adversarial alignment scenarios
/// produced by the 50-agent hardening workflow (generate → independently
/// verify → persist). Each scenario is a pair of operation lists plus the
/// alignment an expert agreed on; the real <see cref="BlockAligner"/> must
/// reproduce it (matched pairs and unmatched sets).
/// </summary>
public class AlignmentScenarioTests
{
    private static readonly JsonSerializerOptions Json = new()
    {
        PropertyNameCaseInsensitive = true
    };

    private static string FixturePath =>
        Path.Combine(AppContext.BaseDirectory, "Fixtures", "alignment-scenarios.json");

    public static IEnumerable<object[]> Scenarios()
    {
        if (!File.Exists(FixturePath))
        {
            yield return [""]; // sentinel — the fixture is generated by the workflow
            yield break;
        }

        var scenarios = JsonSerializer.Deserialize<List<AlignmentScenario>>(File.ReadAllText(FixturePath), Json) ?? [];
        foreach (var scenario in scenarios)
            yield return [JsonSerializer.Serialize(scenario, Json)];
    }

    [Theory]
    [MemberData(nameof(Scenarios))]
    public void Aligner_ReproducesExpectedAlignment(string scenarioJson)
    {
        if (string.IsNullOrEmpty(scenarioJson))
            return; // no fixture yet

        var scenario = JsonSerializer.Deserialize<AlignmentScenario>(scenarioJson, Json)!;

        var left = scenario.Left.Select(o => ToNode(o, OperationSource.OriginalTerraform)).ToList();
        var right = scenario.Right.Select(o => ToNode(o, OperationSource.TargetTerraform)).ToList();

        var result = BlockAligner.Align(left, right);

        var actualMatches = result.Matched.Select(m => (m.LeftIndex, m.RightIndex)).ToHashSet();
        var expectedMatches = scenario.ExpectedMatches.Select(m => (m.LeftIndex, m.RightIndex)).ToHashSet();

        Assert.True(
            actualMatches.SetEquals(expectedMatches),
            $"[{scenario.Name}] matched pairs\n  expected: {Format(expectedMatches)}\n  actual:   {Format(actualMatches)}");

        Assert.True(
            result.UnmatchedLeft.ToHashSet().SetEquals(scenario.ExpectedUnmatchedLeft),
            $"[{scenario.Name}] unmatched-left expected [{string.Join(",", scenario.ExpectedUnmatchedLeft)}] got [{string.Join(",", result.UnmatchedLeft)}]");

        Assert.True(
            result.UnmatchedRight.ToHashSet().SetEquals(scenario.ExpectedUnmatchedRight),
            $"[{scenario.Name}] unmatched-right expected [{string.Join(",", scenario.ExpectedUnmatchedRight)}] got [{string.Join(",", result.UnmatchedRight)}]");
    }

    private static OperationNode ToNode(AlignmentOp op, OperationSource source) => new()
    {
        Source = source,
        Method = (op.Method ?? "").ToUpperInvariant(),
        UrlTemplate = op.Url ?? "",
        OperationId = op.Id ?? "",
        ParameterKeys = (op.Params ?? []).OrderBy(k => k, StringComparer.Ordinal).ToList()
    };

    private static string Format(IEnumerable<(int, int)> pairs) =>
        "{" + string.Join(", ", pairs.OrderBy(p => p.Item1).Select(p => $"{p.Item1}->{p.Item2}")) + "}";
}

public sealed class AlignmentScenario
{
    public string Name { get; set; } = "";
    public string? Rationale { get; set; }
    public List<AlignmentOp> Left { get; set; } = [];
    public List<AlignmentOp> Right { get; set; } = [];
    public List<AlignmentMatch> ExpectedMatches { get; set; } = [];
    public List<int> ExpectedUnmatchedLeft { get; set; } = [];
    public List<int> ExpectedUnmatchedRight { get; set; } = [];
}

public sealed class AlignmentOp
{
    public string? Method { get; set; }
    public string? Url { get; set; }
    public string? Id { get; set; }
    public List<string>? Params { get; set; }
}

public sealed class AlignmentMatch
{
    [JsonPropertyName("leftIndex")] public int LeftIndex { get; set; }
    [JsonPropertyName("rightIndex")] public int RightIndex { get; set; }
}
